###################################################
# RTutor.AI, a Shiny app for chating with your data
# Author: Xijin Ge    gexijin@gmail.com
# Dec. 6-12, 2022.
###################################################



###################################################
# Global variables
###################################################

release <- 0.1 # RTutor
uploaded_data <- "Upload"
min_query_length <- 6  # minimum # of characters
max_query_length <- 500 # max # of characters
language_model <- "text-davinci-003"
default_temperature <- 0.1
pre_text <- "Generate R code, not R Markdown. "


# if this file exists, running on the server. Otherwise local.
# this is used to change app behavior.
on_server <- "on_server.txt"


#' Move an element to the front of a vector
#'
#' The response from GPT3 sometimes contains strings that are not R commands.
#'
#' @param v is the vector
#' @param e is the element
#'
#' @return Returns a reordered vector
move_front <- function(v, e){
  ix <- which(v == e)

  # if found, move to the beginning.
  if(length(ix) != 0) {
    v <- v[-ix]
    v <- c(e, v)
  }
  return(v)
}


#' Prepare User input.
#'
#' The response from GPT3 sometimes contains strings that are not R commands.
#'
#' @param txt A string that stores the user input.
#' @param selected_data Name of the dataset.
#'
#' @return Returns a cleaned up version, so that it could be sent to GPT.
prep_input <- function(txt, selected_data){
  # if too short, do not send. 
  if(nchar(txt) < min_query_length || nchar(txt) > max_query_length) {
    return(NULL)
  }

  if(!is.null(selected_data)) {
    if(selected_data == uploaded_data) {
      selected_data <- "df"
    }
    txt <- paste("Use the", selected_data, "data frame. ", txt)
  }
  txt <- paste(pre_text, txt)

  # If the last character is not a stop, add it. 
  # Otherwise, GPT3 will add a sentence.

  # The following 5 lines were generated by ChatGPT!!!!!
  # Check if the last character is not a period
  if(substr(txt, nchar(txt), nchar(txt)) != ".") {
    # If the last character is not a period, add a period to the end of the string
    txt <- paste(txt, ".", sep = "")
  }

  return(txt)
}


#' Clean up R commands generated by GTP
#'
#' The response from GTP3 sometimes contains strings that are not R commands.
#'
#' @param cmd A string that stores the completion from GTP3.
#' @param selected_data, name of the selected dataset. 
#' @return Returns a cleaned up version, so that it could be executed as R command.
clean_cmd <- function(cmd, selected_data){
  # simple way to check
  if(grepl("That model is currently overloaded with other requests.|Error:", cmd)) {
    return(NULL)
  }
  # Use cat to converts \n to newline
  # use capture.output to get the string
  cmd <- capture.output(
    cat(cmd)
  )

  #cmd is a vector. Each element is a line.

  # sometimes it returns RMarkdown code.
  cmd <- gsub("```", "", cmd)

  # remove empty lines
  cmd <- cmd[cmd != ""]

  # replace install.packages by "#install.packages"
  cmd <- gsub("install.packages", "#install.packages", cmd)

  # if data is uploaded, add a line to get the data.
  if(selected_data == uploaded_data) {
    cmd <- c("df <- user_data()$df", cmd)
  }

  return(cmd)

}


###################################################################
# Prepare data
###################################################################
demos <- c(
  ' ... ' = 'Example requests',

  'Boxplot, ggplot2' = "Use ggplot2 to create a boxplot of hwy vs. class. 
Color by class.
Add jitter",

  'Correlation with context' = "Calculate the correlation coefficient of cty vs hwy.
Repeat that after log transformation.
Collect these results and show them.",

"High level Qs, 1" = "Are suvs more fuel efficient than compact cars?",

  'ANOVA, after log' = "Conduct ANOVA of log-transformed hwy by class and drv.",

  "Barplot, summarized" = "Calculate average cty by year and class.
Then use ggplot2 to create a barplot of average mpg by class,
colored by year. The years should be side by side.",

  "Analysis, step by step" = "Only keep cars with hwy bigger than 15, but less than 40.
Add 0.5 to cty.
Perform log transformation on cty.
Raise hwy to the second power.
Calculate correlation coefficient of transformed hwy and cty.",

  "Correlation heatmap" = "Create a correlation map of all the columns that contain numbers.",

  'Regression, simple' = "Build a regression model of hwy.",

  'Regression, specific' = "Build a regression model of hwy based on cyl, displ, drv, and class. 
Give me diagnostic plots.",

  "Analysis, complex" = "hwy and cty represent miles per gallon (MPG) on the highway and in the city, respectively.
Only keep cars more efficient than 15 MPG, but less than 40, on the highway.
Add 0.5 to city MPG for correction.
Perform log transformation on city MPG.
Raise highway MPG to the second power.
Calculate correlation coefficient of  the two transformed variables.",

  "Neural network" = "Build a neural network model to predict 
hwy based on displ, cyl, and class.  
Use the nnet package. Plot the distribution of residuals.",

  "Scatter, refined" = "Use ggplot2. Plot hwy vs. cty, colored by class. 
Change shape by drv. Change size by displ.
Change x label to 'Highway mpg'.
Change y label to 'City mpg'.
Change background to white.
Increase font for labels to 15.
Remove all grids.",

"High level Qs, 2" = "Are hwy increasing over the years?",
"Ask for info, R packages" = "Show me the R packages for regression.",
"Ask for info, demo" = "Show me how to do model-based clustering.",
"Hierarchical clustering" = "Conduct hierarchical clustering"



)

demo_questions <- c(
'Example questions:' = "Example questions:",
'Lookup R package' = "List popular R packages for forecast.",
'Explain concepts' = "What is cook's distance?",
'Explain algorithm' = "How does k-means algorith work?",
'How to, methods' = "How do you choose k in k-means clustering?",
'How to, evaluation' = "How do you evaluate the results of multiple linear regression?",
'How to, interpretation' = "What does P value = 0.04 mean in t-test?",
'Statistic test' = "What statistics test to use to examine the 
correlation of two categorical variable?"
)




# prepare a list of available data sets.
datasets <- data()$results[, 3] # name of datasets
datasets <- gsub(" .*", "", datasets)
datasets <- move_front(datasets, "state.x77")
datasets <- move_front(datasets, "iris")
datasets <- move_front(datasets, "mtcars")
datasets <- move_front(datasets, "diamonds")
datasets <- move_front(datasets, "mpg")

# if dataset is not data frame or matrix, remove.
ix <- sapply(
  datasets, 
  function(x) {
    eval(
      parse(
        text = paste(
          "is.data.frame(",
          x,
          ") | is.matrix(",
           x, 
           ")"
        )
      )
    )
  }
)

datasets <- datasets[which(ix)]

# append a dummy value, used when user upload their data.
datasets <- c(datasets, uploaded_data)

# Generated by ChatGPT
jokes <- c(
  "Why did the tomato turn red? Because it saw the salad dressing. - ChatGPT",
  "Why was the belt arrested? Because it held up a pair of pants. - ChatGPT",
  "Why was the math book sad? Because it had too many problems. - ChatGPT",
  "Why was the statistician's favorite method of transportation a bus? Because it had a lot of data. - ChatGPT",
  "Why did the tomato turn red? Because it saw the salad dressing. - ChatGPT",
  "Why was the math book upset? Because it was having a negative number of pages. - ChatGPT",
  "Why was the math book happy? Because it had lots of solutions. - ChatGPT",
  "Why couldn't the bicycle stand up by itself? Because it was two-tired. - ChatGPT",
  "Why do statisticians enjoy spending time with their data? Because they're data-driven individuals. - ChatGPT",
  "Why do statisticians like playing with their data? Because they have mean jokes. - ChatGPT",
  "Why do statisticians have a tough time at parties? Because they're always trying to fit in. - ChatGPT",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. -ChatGPT",
  "Don't let yesterday take up too much of today. -ChatGPT",
  "If you want to live a happy life, tie it to a goal, not to people or things. -ChatGPT",
  "If you can dream it, you can do it.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. -ChatGPT",
  "The only way to do great work is to love what you do. -ChatGPT",
  "The only limit to our realization of tomorrow will be our doubts of today. -ChatGPT",
  "You miss 100% of the shots you don't take. -ChatGPT",
  "Your time is limited, don't waste it living someone else's life. -ChatGPT",
  "Hardships often prepare ordinary people for an extraordinary destiny. -ChatGPT",
  "Success is not how high you have climbed, but how you make a positive difference to the world. -ChatGPT",
  "Happiness is not something ready-made. It comes from your own actions. -ChatGPT",
  "The only way to do great work is to be passionate about what you do. -ChatGPT",
  "Believe you can and you're halfway there. -ChatGPT",
  "The only way to achieve the impossible is to believe it is possible. -ChatGPT",
  "Do what you can, with what you have, where you are. -ChatGPT",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. -ChatGPT",
  "Life is not about waiting for the storm to pass, but learning to dance in the rain. -ChatGPT",
  "The biggest adventure you can take is to live the life of your dreams. -ChatGPT",
  "If opportunity doesn't knock, build a door. -ChatGPT",
  "The only limit to our realization of tomorrow will be our doubts of today. -ChatGPT",
  "The only true limit to our realization of tomorrow is in today's doubts and fears. -ChatGPT",
  "Don't watch the clock; do what it does. Keep going. -ChatGPT",
  "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. -ChatGPT",
  "You may be the only person left who believes in you, but it's enough. It takes just one star to pierce a universe of darkness. Never give up. -ChatGPT",
  "Be the change you wish to see in the world. -ChatGPT",
  "The only way to discover the limits of the possible is to go beyond them into the impossible. -ChatGPT",
  "Success is not in what you have, but who you are. -ChatGPT",
  "Success is not how much money you make, but the difference you make in people's lives. -ChatGPT",
  "The only limit to our realization of tomorrow will be the doubts of today. -ChatGPT",
  "Statistics are like a bikini. What they reveal is suggestive, but what they conceal is vital. - Aaron Levenstein",
  "There are three kinds of lies: lies, damned lies, and statistics. - Benjamin Disraeli",
  "In God we trust, all others must bring data. - W. Edwards Deming",
  "Statistics is the grammar of science. - Karl Pearson",
  "A single death is a tragedy; a million deaths is a statistic. - Joseph Stalin",
  "Chance is the pseudonym of God when he does not want to sign his work. - Anatole France",
  "Statistics are like a lamp that illuminates the past and the present, but only reveals the future. - George E. P. Box",
  "Statistics are human beings with the tears wiped off. - Paul Brodeur",
  "The only thing more dangerous than ignorance is arrogance. - Albert Einstein",
  "The best thing about being a statistician is that you get to play in everyone's backyard. - John Tukey"
)



#' Clean up API key character
#'
#' The response from GPT3 sometimes contains strings that are not R commands.
#'
#' @param api_key is a character string
#'
#' @return Returns a string with api key.
clean_api_key <- function(api_key) {
  # remove spaces
  api_key <- gsub(" ", "", api_key)
  return(api_key)
}


#' Validate API key character
#'
#' The response from GPT3 sometimes contains strings that are not R commands.
#'
#' @param api_key is a character string
#'
#' @return Returns TRUE or FALSE
validate_api_key <- function(api_key) {
  valid <- TRUE
  # if 51 characters, use the one in the file
  if (nchar(api_key) != 51) {
    valid <- FALSE
  }
  return(valid)
}


# get API key from environment variable.
api_key_global <- Sys.getenv("OPEN_API_KEY")
key_source <- "from OS environment variable."
# If there is an key file in the current folder, use that instead.
if (file.exists("api_key.txt")) {
  api_key_file <- readLines("api_key.txt")
  api_key <- clean_api_key(api_key_file)

  # if valid, replace with file
  if(validate_api_key(api_key_file)) {
    api_key_global <- api_key_file
    key_source <- "from file."
  }

}